# @package _global_
export:
  # Export data type
  dtype: "bf16"  # or "fp16", "fp32"
  
  # Save options
  save_mixed: true      # save both original and GloBE versions
  save_safetensors: true # use safetensors format
  
  # Compression
  compress: false       # compress exported weights
  
  # Validation
  validate_export: true # validate exported model
  
  # Output paths
  output_dir: "outputs/exported_models"
  model_name: null      # auto-generate if null
  
  # HuggingFace Hub
  push_to_hub: false
  hub_repo_id: null
  hub_private: true
  
  # Metadata
  save_config: true     # save GloBE configuration
  save_metrics: true    # save reconstruction metrics
